version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80" 
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=ventureDb;Username=user;Password=password;

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ventureDb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
